apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: monitoring
  labels:
    app: spring-app
spec:
  selector:
    app: spring-app
  ports:
  - name: http
    port: 9991
    targetPort: 9991
